---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  Test: 0
  Test::More: 0.88
  bigint: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.133380'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-Numbers
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  perl: 5.006
  strict: 0
  vars: 0
  warnings: 0
resources:
  repository: git://github.com/neilbowers/Lingua-EN-Numbers.git
version: 1.06
